import { DefaultTheme } from "styled-components";

export const theme: DefaultTheme = {
  colors: {
    "type-bug": "#8CB230",
    "type-dragon": "#0F6AC0",
    "type-dark": "#58575F",
    "type-electric": "#EED535",
    "type-fairy": "#ED6EC7",
    "type-fighting": " #D04164",
    "type-fire": "#FD7D24",
    "type-flying": " #748FC9",
    "type-ghost": "#556AAE",
    "type-grass": "#62B957",
    "type-ground": "#DD7748",
    "type-ice": "#61CEC0",
    "type-normal": " #9DA0AA",
    "type-poison": "#A552CC",
    "type-psychic": "#EA5D60",
    "type-rock": "#BAAB82",
    "type-steel": "#417D9A",
    "type-water": "#4A90DA",

    "background-type-bug": " #8BD674",
    "background-type-dragon": " #7383B9",
    "background-type-dark": " #6F6E78",
    "background-type-electric": " #F2CB55",
    "background-type-fairy": " #EBA8C3",
    "background-type-fighting": " #EB4971",
    "background-type-fire": " #FFA756",
    "background-type-flying": " #83A2E3",
    "background-type-ghost": " #8571BE",
    "background-type-grass": " #8BBE8A",
    "background-type-ground": " #F78551",
    "background-type-ice": " #91D8DF",
    "background-type-normal": " #B5B9C4",
    "background-type-poison": " #9F6E97",
    "background-type-psychic": " #FF6568",
    "background-type-rock": " #D4C294",
    "background-type-steel": " #4C91B2",
    "background-type-water": " #58ABF6",

    "background-white": "#FFF",
    "background-default-input": "#F2F2F2",
    "background-pressed-input": "#E2E2E2",
    "background-modal": "#17171B.5",

    "text-white": "#FFFFFF",
    "text-black": "#17171B",
    "text-gray": "#747476",
    "text-number": "#17171B.6",

    "height-short": "#FFC5E6",
    "height-medium": "#AEBFD7",
    "height-tall": "#AAACB8",

    "weight-light": "#99CD7C",
    "weight-medium": "#57B2DC",
    "weight-heavy": "#5A92A5",
  },
  fontSizes: {
    "font-size-32": 32,
    "font-size-26": 26,
    "font-size-16": 16,
    "font-size-12": 12,
  },
  fontWeights: {
    "font-weight-light": "Inter_300Light",
    "font-weight-regular": "Inter_400Regular",
    "font-weight-bold": "Inter_700Bold",
  },
};
